name: redically_local
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_form_builder: ^7.1.0
  image_picker: ^0.8.4+9
  permission_handler: ^9.0.1
#  location: ^4.3.0
  form_builder_validators: ^7.4.0
  pin_code_text_field: ^1.8.0
  pin_code_fields: ^7.3.0
  #  http: ^0.13.4
  fluttertoast: ^8.0.8
  shared_preferences: ^2.0.13
  sizer: ^2.0.15
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  extended_image: ^6.2.1
  #  flutter_credit_card: ^3.0.1
  #  dotted_border: ^2.0.0+2
  dio: ^4.0.4
  #  credit_card_type_detector: ^2.0.0
  font_awesome_flutter: ^9.2.0
#  shimmer: ^2.0.0
  #  carousel_pro_nullsafety: ^1.0.2
#  flutter_rating_bar: ^4.0.0
  cached_network_image: ^3.2.0
  intl: ^0.17.0
  #  awesome_dialog: ^2.1.2
  #  hive: ^2.0.6
  #  hive_flutter:
#  path_provider:
#  auto_size_text: ^3.0.0
  #  scan: ^1.6.0
  #  google_maps_place_picker_mb: ^2.0.0-mb.18
#  country_code_picker: ^2.0.2
  #  chips_choice_null_safety: ^2.0.6
  #  flutter_branch_sdk: ^5.0.0
  package_info_plus: ^1.4.2
  #  sign_in_with_apple: ^3.3.0
  #  google_sign_in: ^5.3.0
  #  flutter_facebook_auth: ^4.2.1
  #  signalr_core: ^1.1.1
#  flutter_chat_bubble: ^2.0.0
  #  flutter_keyboard_visibility: ^5.2.0
  device_info_plus: ^3.2.3
  #  another_xlider: ^1.0.1+2
  # time_range_picker: ^2.1.0
  #  grouped_list: ^5.0.1
  #  mask_text_input_formatter: ^2.3.0
  #  expandable: ^5.0.1
#  modal_bottom_sheet: ^2.0.1
  #  map_picker: ^0.0.3
#  google_maps_flutter: ^2.1.6
#  geolocator: ^8.2.1
  flutter_staggered_grid_view: ^0.6.1
  flutter_time_range: ^0.0.3
  timeago: ^3.2.2
#  video_player: ^2.4.5
#  video_compress: ^3.1.1
  camera: ^0.10.0+1
#  video_editor_sdk: ^2.6.0
#  photo_editor_sdk: ^2.6.0
  photo_gallery: ^1.1.1
  widget_to_image: ^2.0.0
  extended_sliver: ^2.1.3
  flutter_custom_clippers: ^2.0.0
  intl_phone_number_input: ^0.7.0+2
  scroll_date_picker: ^3.5.2
  flutter_switch: ^0.3.2
  lottie: ^2.2.0
  #  mapbox_gl: ^0.16.0
  file_picker:
  image_cropper: ^2.0.3
#  custom_map_markers: ^0.0.2+1
  jwt_decoder: ^2.0.1
#  flutter_cache_manager: ^3.3.0
#  firebase_dynamic_links: ^4.3.4
#  firebase_core: ^1.20.1
#  video_thumbnail: ^0.5.2
#  firebase_messaging: ^12.0.3
#  flutter_local_notifications: ^9.8.0+1
#  google_maps_webservice: ^0.0.20-nullsafety.5
#  hashtagable: ^2.1.0
  url_launcher: ^6.1.2
  signalr_core: ^1.1.1
  http: ^0.13.4
#  flutter_keyboard_visibility: ^5.3.0
  sliding_up_panel: ^2.0.0+1
  share_plus: ^4.4.0
  easy_debounce: ^2.0.2+1
  grouped_list: ^5.1.2
  flutter_slidable: ^2.0.0
  flutter_svg: ^1.1.6
  xayn_swipe_it: ^1.0.4
  collection_ext: ^1.0.0
  animate_do: ^3.0.2
  flutter_calendar_carousel: ^2.4.1
  pie_chart: ^5.3.2
  flutter_neumorphic: ^3.2.0
  #  cached_video_player: ^2.0.3
  #  flutter_social_content_share: ^1.0.2
  #  device_info_plus: ^4.0.1
#  linkwell: ^2.0.6
#  any_link_preview: ^2.0.9
  flutter_launcher_icons: ^0.11.0
  qr_code_scanner: ^1.0.1
  vibration: ^1.7.5

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/icons/
    - assets/

  fonts:
    - family: LexendPeta-Black
      fonts:
        - asset: assets/fonts/LexendPeta-Black.ttf

    - family: LexendPeta-Bold
      fonts:
        - asset: assets/fonts/LexendPeta-Bold.ttf

    - family: LexendPeta-SemiBold #600
      fonts:
        - asset: assets/fonts/LexendPeta-SemiBold.ttf

    - family: LexendPeta-ExtraBold #800
      fonts:
        - asset: assets/fonts/LexendPeta-ExtraBold.ttf

    - family: LexendPeta-ExtraLight
      fonts:
        - asset: assets/fonts/LexendPeta-ExtraLight.ttf

    - family: LexendPeta-Light
      fonts:
        - asset: assets/fonts/LexendPeta-Light.ttf

    - family: LexendPeta-Medium
      fonts:
        - asset: assets/fonts/LexendPeta-Medium.ttf

    - family: LexendPeta-Regular #500
      fonts:
        - asset: assets/fonts/LexendPeta-Regular.ttf

    - family: LexendPeta-Thin #400
      fonts:
        - asset: assets/fonts/LexendPeta-Thin.ttf
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/RRFAppIcon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/RRFAppIcon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/RRFAppIcon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/RRFAppIcon.png"